### PR TITLE
✨ Physics hands

### LINKED ISSUE #160: ✨Custom Grab System

### LINKED ISSUE #172: 🐛 hand grabing not working sometimes

### LINKED ISSUE #174: 🐛 Can put items under the map

### LINKED ISSUE #217: 🐛Cant pick up shields

### PR DESCRIPTION
**Pull request by Bulldoger-true**
## Content

*Describe what was changed / fixed here. IE: Updated animation to be centered around the players origin, caught exception, added particle system...*

### Added
`Assets/Fonts/Parisienne-Regular SDF.asset` : Don't know why this is here, but can't really undo the changes. Choose the different file if this causes a merge conflict.
`Assets/Scripts/Player/PhysicsHands/GrabLogic.cs` : Logic for the grab system
`Assets/Scripts/Player/PhysicsHands/RigidbodyTransformFollower.cs` : A script used for the original physics hand.

### Updated
`Assets/Samples/XR Hands/1.4.1/Gestures/Examples/Hand Shapes/Grab Hand Shape.asset` : Changed gesture to better resemble a grab.
`ProjectSettings/DynamicsManager.asset` : Updated collision matrix (collision between layers)
`ProjectSettings/TagManager.asset` : Added new layer "Physics Hands" which does not collide with the player
`Assets/Prefabs/PlayerRig/PlayerRig.prefab` No idea why this is here- it shows the can quick cast variable being gone. If this causes a merge conflict, choose the other version to keep.

## Testing

The feature / Bugfix can be testing by following these steps:

1. Add kinematic rigidbodies to the Palm game objects of the hands, under the X Hand game object
2. Add the script GrabLogic to the same game object
3. Set grab range to desired value, around 0.3 usually, and drag in the rigidbody and transform of the object that is going to be grabbing things.
4. Add "Player" layer to the layers to ignore array
5. Under the Gesture Detection game object, go to the one named "X Grab" (for both hands) and configure this script as follows:
image
6. Go into the scene and attempt to grab an object with a non kinematic rigidbody by closing your fist. Opening it again releases it. You cannot push it through walls as it will release the object.

Closes #160
Closes #172
Closes #174
Closes #217

### CODE REVIEW

File: Assets/Scripts/Player/PhysicsHands/GrabLogic.cs [hunk 1]
```diff
@@ -0,0 +1,144 @@
+using UnityEngine;
+using System.Collections.Generic;
+using Unity.XR.CoreUtils.Datums;
+using System;
+
+namespace RogueApeStudios.SecretsOfIgnacios
```
Comment (Timsel1) [inline Assets/Scripts/Player/PhysicsHands/GrabLogic.cs]: Incorrect namespace

File: Assets/Scripts/Player/PhysicsHands/GrabLogic.cs [hunk 2]
```diff
@@ -0,0 +1,144 @@
...
+                    EndGrab();
+                }
+            }
+
+        }
+
+
+        public void CheckForGrabbables()
+        {
+            Debug.Log("i'm gonna grab u!!!!1");
```
Comment (Timsel1) [inline Assets/Scripts/Player/PhysicsHands/GrabLogic.cs]: Try to remove logs if they don't provide specific info, this should not be necessary in dev after approval

File: Assets/Scripts/Player/PhysicsHands/GrabLogic.cs [hunk 3]
```diff
@@ -0,0 +1,144 @@
...
+                List<Rigidbody> potentialRigidbodies = new List<Rigidbody>();
+
+                
+                
+                spherecasthits = Physics.SphereCastAll(_grabCenter.position, _grabRange, Vector3.forward, _grabRange,_grabLayerMask);
+
+                foreach (RaycastHit hit in spherecasthits)
+                {
+                    GameObject hitObject = hit.collider.gameObject;
+                    Rigidbody oldrb;
```
Comment (Timsel1) [inline Assets/Scripts/Player/PhysicsHands/GrabLogic.cs]: Watch naming of variables oldrb -> oldRb (camelCase for local variables)

File: Assets/Scripts/Player/PhysicsHands/GrabLogic.cs [hunk 4]
```diff
@@ -0,0 +1,144 @@
...
+            _grabbedJoint.gameObject.layer = 14;
+        }
+
+        public void EndGrab()
+        {
+            if (_grabbedRb != null) { 
+                Debug.Log("i'm gonna stop grab u!!!!1");
+                _grabbedJoint.gameObject.layer = _oldGrabbableLayer;
+                //remove a configurable joint
+                Destroy(_grabbedJoint);
```
Comment (Timsel1) [inline Assets/Scripts/Player/PhysicsHands/GrabLogic.cs:104]: Would it be possible to reuse joints? If not ignore this comment

File: Assets/Scripts/Player/PhysicsHands/RigidbodyTransformFollower.cs [hunk 5]
```diff
@@ -0,0 +1,99 @@
+using System.Diagnostics;
+using UnityEngine;
+using System.Collections.Generic;
+
+
+namespace RogueApeStudios.SecretsOfIgnacios
```
Comment (Timsel1) [inline Assets/Scripts/Player/PhysicsHands/RigidbodyTransformFollower.cs]: Wrong namespace

File: Assets/Scripts/Player/PhysicsHands/RigidbodyTransformFollower.cs [hunk 6]
```diff
@@ -0,0 +1,99 @@
...
+        }
+
+        private void UpdateRotation(Rigidbody rb, Transform ttransform)
+        {
+            /*var rotation = Quaternion.FromToRotation(rb.transform.forward, ttransform.forward).eulerAngles * -0.05f;
+            print(rotation);
+            rb.angularVelocity = rotation;*/
+            // Rotations stack right to left,
+            // so first we undo our rotation, then apply the target.
+            var delta = ttransform.rotation * Quaternion.Inverse(rb.rotation);
```
Comment (Timsel1) [inline Assets/Scripts/Player/PhysicsHands/RigidbodyTransformFollower.cs]: Does this not give an error? (tt)
```c#
var delta = ttransform.rotation * Quaternion.Inverse(rb.rotation);
```

**Review by Timsel1 — CHANGES_REQUESTED** [review]
Formatting in both scripts looks off in github, but I'm gonna assume it looks alright in the editor

File: Assets/Scripts/Player/PhysicsHands/RigidbodyTransformFollower.cs (hunk 6 above)
Comment (Bulldoger-true) [reply Assets/Scripts/Player/PhysicsHands/RigidbodyTransformFollower.cs]: no, this is a (albeit oddly named) local variable

File: Assets/Scripts/Player/PhysicsHands/GrabLogic.cs (hunk 4 above)
Comment (Bulldoger-true) [reply Assets/Scripts/Player/PhysicsHands/GrabLogic.cs:104]: Since the joints are put on the grabbed objects, no.

File: Assets/Scripts/Player/PhysicsHands/GrabLogic.cs [hunk 7]
```diff
@@ -3,7 +3,7 @@
 using Unity.XR.CoreUtils.Datums;
 using System;
 
-namespace RogueApeStudios.SecretsOfIgnacios
+namespace RogueApeStudios.SecretsOfIgnacios.Player
```
Comment (Timsel1) [inline Assets/Scripts/Player/PhysicsHands/GrabLogic.cs]: .PhysicsHands

File: Assets/Scripts/Player/PhysicsHands/RigidbodyTransformFollower.cs [hunk 8]
```diff
@@ -3,7 +3,7 @@
 using System.Collections.Generic;
 
 
-namespace RogueApeStudios.SecretsOfIgnacios
+namespace RogueApeStudios.SecretsOfIgnacios.Player
```
Comment (Timsel1) [inline Assets/Scripts/Player/PhysicsHands/RigidbodyTransformFollower.cs]: same as other one

**Review by Timsel1 — CHANGES_REQUESTED** [review]

**Review by Timsel1 — APPROVED** [review]
Approved as a first prototype, it is pretty buggy, I'm sure you know. You also didn't add a description to your pr and forgot to mention I had to turn off old grab in the player prefab, because I feel like it overwrites yours. You can also not throw any objects.
