### PR TITLE
✨ Interactables system

### LINKED ISSUE #58: ✨ Interactable system
System behind items spells can interact with, has the logic of what should happen to these objects. E.g. a box should burn, then be destroyed after a couple of seconds, then a burnt/broken box should be the result.

- [x] #67
- [x] #68
- [x] #69
- [x] #70

### PR DESCRIPTION
**Pull request by Tapardy**
## Content

Earth, Fire, Water and Wind interactables have been made

### Updated
#72 (old water pr)
#73 
#79 
#96 
#97 

## Testing

The feature / Bugfix can be testing by following these steps:

All was previously tested, but you can look at the individual pull requests for information

Closes #58

### CODE REVIEW

File: Assets/Scripts/Interactables/Fire/DestructiveBurning.cs [hunk 1]
```diff
@@ -0,0 +1,87 @@
...
+using Cysharp.Threading.Tasks;
+using UnityEngine;
+using UnityEngine.VFX;
+
+namespace RogueApeStudios.SecretsOfIgnacios.Interactables.Fire
+{
+	internal class DestructiveBurning : FireInteractable
+	{
+		[Header("Burn Settings")] [SerializeField]
+		private float burnTime = 1;
```
Comment (Timsel1) [inline Assets/Scripts/Interactables/Fire/DestructiveBurning.cs:13]: `[SerializeField] _burnTime` if formatting is correct in editor only add the _

File: Assets/Scripts/Interactables/Fire/FireInteractable.cs [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+		{
+			_spellReceiver.OnSpellReceived += HandleSpellReceived;
+		}
+
+		internal override void OnDestroy()
+		{
+			_spellReceiver.OnSpellReceived -= HandleSpellReceived;
+		}
+
+		internal event Action<bool> OnIgnitionToggle;
```
Comment (Timsel1) [inline Assets/Scripts/Interactables/Fire/FireInteractable.cs:25]: Should be above awake

File: Assets/Scripts/Interactables/Water/Fillable.cs [hunk 3]
```diff
@@ -0,0 +1,44 @@
...
+                    Debug.Log(_contentFilled);
+                }
+                if (_contentFilled >= _contentMax)
+                {
+                    _filled = true;
+                }
+            }
+            catch (OperationCanceledException)
+            {
+                Debug.LogError("Cleaning was Canceled");
```
Comment (Timsel1) [inline Assets/Scripts/Interactables/Water/Fillable.cs:33]: "Fill was canceled"

File: Assets/Scripts/Interactables/Water/WaterInteractable.cs [hunk 4]
```diff
@@ -0,0 +1,43 @@
+using System;
+using System.Threading;
+using UnityEngine;
+
+namespace RogueApeStudios.SecretsOfIgnacios.Interactables.Water
+{
+	internal abstract class WaterInteractable : Interactables
```
Comment (Timsel1) [inline Assets/Scripts/Interactables/Water/WaterInteractable.cs:7]: If formatting is correct in the editor this is okay, otherwise format

**Review by Timsel1 — CHANGES_REQUESTED** [review]

**Review by Timsel1 — APPROVED** [review]
